git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: "C"
    command: "czg"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
